# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.forward_x11 = true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y git build-essential tcl tk8.6-dev

    git clone git://git.code.sf.net/p/scid/code /usr/local/scid
    cd /usr/local/scid
    ./configure TCL_INCLUDE="-I/usr/include/tcl8.6/" && make && make install

    git clone https://github.com/official-stockfish/Stockfish.git /usr/local/stockfish
    cd /usr/local/stockfish/src
    make build ARCH=x86-64 && make install
  SHELL
end
