# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.network "private_network", type: "dhcp"

  config.vm.provision "shell", path: "provision/pre.sh"
  config.vm.provision "shell", path: "provision/mesos.sh", privileged: false
  config.vm.provision "shell", path: "provision/go.sh", privileged: false
  config.vm.provision "shell", path: "provision/post.sh"

  config.vm.provision "file", source: "files/start_master.sh", destination: "/home/vagrant/src/mesos/build/start_master.sh"
  config.vm.provision "file", source: "files/start_slave.sh", destination: "/home/vagrant/src/mesos/build/start_slave.sh"
end
