# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision "shell", path: "installdeps.sh"
  config.vm.provision "shell", path: "installgo.sh", privileged: false
end
